### ISSUE TITLE
How to install taxator-tk

### ISSUE THREAD

**Issue by Liuyuxinn** [fungs/taxator-tk#67] opened 2023-06-10 08:45 UTC
Hi,

When i opened the "global build and install guide” ,it showed “404 - page not found”.

How to install taxator-tk and how to use it?

Thanks

**Comment by fungs** [comment] 2023-06-12 09:08
Hi @Liuyuxinn,

you are right, the link in the README seems to be outdated. That was just a link to the core compilation page at https://github.com/fungs/taxator-tk/blob/master/core/BUILD.md I removed it.

The recommended way to install this is using the binary releases (Linux 64 bit) [here](https://github.com/fungs/taxator-tk/tree/master#introduction). These packages should run on most modern Linux systems and come with all the example pipelines and scripts.

Let me know if you need further assistance.

**Comment by vvvaeeee** [comment] 2023-06-13 09:41
Hi,

Now,I can install taxator-tk by using the binary releases.

However,how to download your refpack?

When I opened this links(the example refpacks that you provided) " https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/ ",I could not open large refpacks（"microbial-full_20150430.tar.lz" and  "nonredundant-microbial_20140513.tar.xz"),it showed "You don't have permission to access this resource".


wget -c https://research.bifo.helmholtz-hzi.de/downloads/taxator-tk_refpacks/refseq-viral_67.tar.xz --no-check-certificate

--2023-06-13 11:52:57--  https://research.bifo.helmholtz-hzi.de/downloads/taxator-tk_refpacks/refseq-viral_67.tar.xz
Resolving research.bifo.helmholtz-hzi.de (research.bifo.helmholtz-hzi.de)... 193.175.244.52
Connecting to research.bifo.helmholtz-hzi.de (research.bifo.helmholtz-hzi.de)|193.175.244.52|:443... connected.
WARNING: The certificate of 'research.bifo.helmholtz-hzi.de' is not trusted.
WARNING: The certificate of 'research.bifo.helmholtz-hzi.de' hasn't got a known issuer.
HTTP request sent, awaiting response... 403 Forbidden
2023-06-13 11:53:00 ERROR 403: Forbidden.

Can you help me with my problem?

 And I would like to know what the difference is between the contents of these two files （"microbial-full_20150430.tar.lz" and  "nonredundant-microbial_20140513.tar.xz")？


Thanks

**Comment by fungs** [comment] 2023-06-13 14:34
Hi,

seems like the permission on the files are not set correctly on the download server. I will report this to the research institute hosting the files. Thank you for the notice!

Each example refpack contains some information about how it was built. I would always go for the newer ones. The main source for building these refpacks were the NCBI RefSeq releases. I cannot tell the difference by name, it was a while ago and I strongly recommend to construct your own refpack based on the latest RefSeq release, for instance.

This blog entry might be of some help: https://scienceblog.fungs.de/posts/taxator-tk-marine-refpack/

**Comment by fungs** [comment] 2023-06-23 06:59
I'm sorry @Liuyuxinn , I still don't have feedback from the hosting institute. However, if you can send me an email (see README) with the desired refpacks, I can make them available by other means.

**Comment by vvvaeeee** [comment] 2023-06-23 07:35
Hello! Thank you very much for your reply!
However, what is your email address? I don't seem to find it on README.

**Comment by fungs** [comment] 2023-06-23 08:36
Just use 
![image](https://github.com/fungs/taxator-tk/assets/8776981/118bcbb2-c5b2-454c-9c3a-a69e13779c6f)

**Comment by fungs** [comment] 2023-12-22 16:09
Hi @Liuyuxinn, you probably had already given up or found another solution. Anyway, the issue is now fixed. Better late than never...

The actual issue is that those refpacks are getting old and I don't have the time to curate new ones, in particular as they should be specific to the environments, because otherwise the sequences collections are now forbiddingly large. I will try to curate a general purpose refpack in 2024 and make it accessible in a reproducible and reliable way.

**Comment by vvvaeeee** [comment] 2023-12-23 03:13
Hello，Johannes！
I'm glad to hear from you.
Just as you thought,&nbsp;I used blastn as an alternative method to taxonomically annotate with each bins.&nbsp;
I'm very happy to hear this news that you have solved the previous problem, and in fact I found that there are some false positives in the&nbsp;taxonomy&nbsp;annotation using blastn , I plan to do them&nbsp;again with your software. In the meantime, I'm looking forward to the new refpacks!




L.
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "fungs/taxator-tk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月23日(星期六) 凌晨0:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fungs/taxator-tk] How to install taxator-tk (Issue #67)





 
Hi @Liuyuxinn, you probably had already given up or found another solution. Anyway, the issue is now fixed. Better late than never...
 
The actual issue is that those refpacks are getting old and I don't have the time to curate new ones, in particular as they should be specific to the environments, because otherwise the sequences collections are now forbiddingly large. I will try to curate a general purpose refpack in 2024 and make it accessible in a reproducible and reliable way.

**Comment by fungs** [comment] 2023-12-29 18:17
A note for better understanding: taxonomic classification with taxator-tk is a two-step procedure and as a first step it relies on an aligner such as LAST or Blast (blastn or blastp). There are example workflows for those aligners (including all binaries) using the refpack as a reference collection to search through.

If you want to do conservative prediction using the RPA assignment algorithm, you can also run that on your blastn results, given that you provide the alignments in the correct tabular format and a corresponding taxonomy mapping with NCBI taxonomy dump. Having said that, getting these data right is usually more work than running both steps with one of the standard workflows.

Happy (Western) New Year!

**Closed by fungs** 2023-12-29 18:17 UTC
